// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAllAccounts: () => __TAURI_INVOKE<AuthAccount[]>("get_all_accounts"),
	addAccount: () => typedError<AuthAccount, string>(__TAURI_INVOKE("add_account")),
	removeAccount: (uuid: string) => __TAURI_INVOKE<void>("remove_account", { uuid }),
	ensureAssets: (version: string) => typedError<null, string>(__TAURI_INVOKE("ensure_assets", { version })),
	getVersions: (showSnapshots: boolean | null) => typedError<GameVersion[], string>(__TAURI_INVOKE("get_versions", { showSnapshots })),
	refreshAccount: (uuid: string) => typedError<AuthAccount, string>(__TAURI_INVOKE("refresh_account", { uuid })),
	getSkinUrl: (uuid: string) => typedError<string, string>(__TAURI_INVOKE("get_skin_url", { uuid })),
	getPatchNotes: (count: number | null) => typedError<PatchNote[], string>(__TAURI_INVOKE("get_patch_notes", { count })),
	getPatchContent: (contentPath: string) => typedError<string, string>(__TAURI_INVOKE("get_patch_content", { contentPath })),
	launchGame: (version: string, uuid: string | null, server: string | null, debugEnabled: boolean | null, installPath: string | null) => typedError<string, string>(__TAURI_INVOKE("launch_game", { version, uuid, server, debugEnabled, installPath })),
	getClientLogs: () => typedError<string[], null>(__TAURI_INVOKE("get_client_logs")),
	loadLauncherSettings: () => __TAURI_INVOKE<LauncherSettings>("load_launcher_settings"),
	setLauncherLanguage: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_launcher_language", { language })),
	setKeepLauncherOpen: (keep: boolean) => typedError<null, string>(__TAURI_INVOKE("set_keep_launcher_open", { keep })),
	setLaunchWithConsole: (launch: boolean) => typedError<null, string>(__TAURI_INVOKE("set_launch_with_console", { launch })),
	pingServer: (address: string) => __TAURI_INVOKE<ServerStatus>("ping_server", { address }),
	loadServers: () => __TAURI_INVOKE<SavedServer[]>("load_servers"),
	saveServers: (servers: SavedServer[]) => typedError<null, string>(__TAURI_INVOKE("save_servers", { servers })),
	loadInstallations: () => typedError<Installation[], InstallationError>(__TAURI_INVOKE("load_installations")),
	createInstallation: (payload: InstallationDraft) => typedError<Installation, InstallationError>(__TAURI_INVOKE("create_installation", { payload })),
	deleteInstallation: (id: string) => typedError<null, InstallationError>(__TAURI_INVOKE("delete_installation", { id })),
	duplicateInstallation: (oldId: string, payload: InstallationDraft) => typedError<Installation, InstallationError>(__TAURI_INVOKE("duplicate_installation", { oldId, payload })),
	editInstallation: (id: string, payload: InstallationDraft) => typedError<Installation, InstallationError>(__TAURI_INVOKE("edit_installation", { id, payload })),
	getDownloadedVersions: () => __TAURI_INVOKE<string[]>("get_downloaded_versions"),
};

/* Types */
export type AuthAccount = {
	username: string,
	uuid: string,
	access_token: string,
	expires_at: number,
};

export type Directory = string;

export type GameVersion = {
	id: string,
	version_type: string,
};

export type Id = string;

export type Installation = {
	id: Id,
	name: Name,
	version: Version,
	last_played: number | null,
	created_at: TimeStamp,
	directory: Directory,
	width: number,
	height: number,
	is_latest: boolean,
};

export type InstallationDraft = {
	name: string,
	version: string,
	directory: string,
	width: number,
	height: number,
};

export type InstallationError = { kind: "InvalidName" } | { kind: "NameTooLong"; detail: number } | { kind: "InvalidPath" } | { kind: "InvalidCharacter"; detail: string } | { kind: "ReservedName"; detail: string } | { kind: "DirectoryAlreadyExists" } | { kind: "InstallNotFound"; detail: Id } | { kind: "Io"; detail: string } | { kind: "Json"; detail: string } | { kind: "Other"; detail: string };

export type LauncherSettings = {
	language: string,
	keepLauncherOpen: boolean,
	launchWithConsole: boolean,
};

export type Name = string;

export type PatchNote = {
	title: string,
	version: string,
	date: string,
	summary: string,
	image_url: string,
	entry_type: string,
	content_path: string,
};

export type SavedServer = {
	name: string,
	address: string,
	category?: string,
};

export type ServerStatus = {
	online: boolean,
	players: number,
	max_players: number,
	ping_ms: number,
	motd: string,
	version: string,
};

export type TimeStamp = number;

export type Version = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

